// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package openapi

// OpenIDConfigurationSchema defines model for OpenIDConfigurationSchema.
type OpenIDConfigurationSchema struct {
	// AuthorizationEndpoint http://localhost:1234/op/auth
	AuthorizationEndpoint string `json:"authorization_endpoint"`

	// Issuer http://localhost:1234/op
	Issuer string `json:"issuer"`

	// RevocationEndpoint http://localhost:1234/op/revoke
	RevocationEndpoint string `json:"revocation_endpoint"`

	// TokenEndpoint http://localhost:1234/op/token
	TokenEndpoint string `json:"token_endpoint"`

	// UserinfoEndpoint http://localhost:1234/op/userinfo
	UserinfoEndpoint string `json:"userinfo_endpoint"`
}
