openapi: 3.0.3
info:
  title: Open ID Connect App
  description: |-
    This is the OIDC OpenID API documentation.
  termsOfService: https://localhost:1234
  contact:
    email: morning.night.dream@example.com
  license:
    name: MIT
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:1234
tags:
  - name: OP
    description: OpenID Provider
  - name: RP
    description: Relying Party
paths:
  /op/.well-known/openid-configuration:
    get:
      tags:
        - OP
      summary: OpenID Provider Configuration
      description: OpenID Provider Configuration
      operationId: openIDConfiguration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenIDConfigurationSchema'
        '500':
          description: Internal Server Error
  /op/auth:
    get:
      tags:
        - OP
      summary: Authentication Request
      description: Authentication Request
      operationId: auth
      responses:
        '302':
          description: Found
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: http://localhost:1234/rp/auth/callback
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: api-key
      in: header
  schemas:
    OpenIDConfigurationSchema:
      type: object
      properties:
        issuer:
          type: string
          description: http://localhost:1234/op
          format: uri
          example: http://localhost:1234/op
        authorization_endpoint:
          type: string
          description: http://localhost:1234/op/auth
          format: uri
          example: http://localhost:1234/op/auth
        token_endpoint:
          type: string
          description: http://localhost:1234/op/token
          format: uri
          example: http://localhost:1234/op/token
        userinfo_endpoint:
          type: string
          description: http://localhost:1234/op/userinfo
          format: uri
          example: http://localhost:1234/op/userinfo
        revocation_endpoint:
          type: string
          description: http://localhost:1234/op/revoke
          format: uri
          example: http://localhost:1234/op/revoke
      required:
        - "issuer"
        - "authorization_endpoint"
        - "token_endpoint"
        - "userinfo_endpoint"
        - "revocation_endpoint"
    AuthRequestSchema:
      type: object
      description: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
      properties:
        scopes:
          type: array
          description: https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims
          items:
            type: string
            enum:
              - openid
              - profile
              - email
              - address
              - phone
              - offline_access
        response_type:
          type: string
          enum:
            - code
            - id_token
            - token
            - code id_token
            - code token
            - id_token token
            - code id_token token
        client_id:
          type: string
          description: client_id
          format: uri
          example: client_id
        redirect_uri:
          type: string
          description: http://localhost:1234/rp/auth/callback
          format: uri
          example: http://localhost:1234/rp/auth/callback
        state:
          type: string
          description: state
          example: state
        nonce:
          type: string
          description: nonce
          example: nonce
        response_mode:
          type: string
          enum:
            - query
            - fragment
        display:
          type: string
          enum:
            - page
            - popup
            - touch
            - wap
        prompt:
          type: string
          enum:
            - none
            - login
            - consent
            - select_account
        max_age:
          type: integer
          format: int64
          minimum: 0
        ui_locales:
          type: string
          description: ui_locales
          example: ui_locales
        id_token_hint:
          type: string
          description: id_token_hint
          example: id_token_hint
        login_hint:
          type: string
          description: login_hint
          example: login_hint
        acr_values:
          type: array
          description: acr_values
          items:
            type: string
        code_challenge:
          type: string
          description: code_challenge
          example: code_challenge
        code_challenge_method:
          type: string
          enum:
            - plain
            - S256
      required:
        - "scopes"
        - "response_type"
        - "client_id"
        - "redirect_uri"
        - "state"
        - "nonce"
        - "response_mode"
        - "display"
        - "prompt"
        - "max_age"
        - "ui_locales"
        - "id_token_hint"
        - "login_hint"
        - "acr_values"
        - "code_challenge"
        - "code_challenge_method"
